### ISSUE TITLE
Trackback (most recent call last)

### ISSUE THREAD

**Issue by limonsafayet** [DarrenWestwood/greed#23]
Traceback (most recent call last):
File "core.py", line 168, in <module>
main()
File "core.py", line 111, in main
if update.message.text == receiving_worker.loc.get("menu_cancel"):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by DarrenWestwood** [comment]
Hi @LimonSafayet,

Please can you describe the steps to reproduce the issue in order for me to replicate this on my end?

Kind regards

**Comment by ziftech** [comment]
```
python3 -OO core.py
2022-01-20 23:25:27,148 | Core | core | greed is starting!
2022-01-20 23:25:27,310 | Core | core | Received /start from: 463480229
Traceback (most recent call last):
  File "core.py", line 168, in <module>
    main()
  File "core.py", line 111, in main
    if update.message.text == receiving_worker.loc.get("menu_cancel"):
AttributeError: 'NoneType' object has no attribute 'get'
/Users/ykeranch/dev/python/greed/worker.py:77: SAWarning: relationship 'Order.transaction' will copy column orders.order_id to column transactions.order_id, which conflicts with relationship(s): 'Transaction.order' (copies orders.order_id to transactions.order_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="order"' to the 'Order.transaction' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  self.user = self.session.query(db.User).filter(db.User.user_id == self.chat.id).one_or_none()

**Comment by blockonomics** [comment]
@letstalkbusinezz  @limonsafayet  Feel free to test now .. these issues have been resolved in the latest code
